export const AUTH_TOKEN = 'token'

export const ROOT = ''
export const AUTH = 'auth'
export const LOGIN = 'login'
export const REGISTRATION = 'signUp'
export const NEW_PASSWORD = 'newPassword'
export const MAIN = 'main'
export const EVENTS = 'events'
export const PRODUCTS = 'products'
export const NEW = 'new'
export const EDIT = 'edit'
export const RESULTS = 'results'
export const PROFILE = 'profile'
export const WELCOME = 'welcome'

export const ROOT_URL = '/' + ROOT
export const AUTH_URL = '/' + AUTH
export const LOGIN_URL = '/' + LOGIN
export const REGISTRATION_URL = '/' + REGISTRATION
export const NEW_PASSWORD_URL = '/' + NEW_PASSWORD
export const MAIN_URL = '/' + MAIN
export const EVENTS_URL = '/' + EVENTS
export const PRODUCTS_URL = '/' + PRODUCTS
export const NEW_URL = '/' + NEW
export const EDIT_URL = '/' + EDIT
export const RESULTS_URL = '/' + RESULTS
export const PROFILE_URL = '/' + PROFILE
export const WELCOME_URL = '/' + WELCOME
export const MEMBERS_URL = '/members'

export const MSG_ERROR = 'Ууупс... '
export const MSG_EVENT_GENERATED = 'Событие создано. Вперед!'
export const MSG_LOGIN_SUCCESS = 'Вход успешно выполнен'
export const MSG_REGISTRATION_SUCCESS = 'Регистрация успешна'
export const MSG_EVENT_EDITED = 'Данные успешно обновлены'
export const MSG_EVENT_CREATED = 'Событие создано'
export const MSG_PRODUCTS_UPDATED = 'Данные продукта обновлены'
export const MSG_PRODUCT_DELETED = 'Продукт удален'
export const MSG_UPDATED = 'Обновлено'
export const MSG_PASSWORD_UPDATED = 'Пароль сменен'
export const MSG_MEMBER_ADDED = 'Участник добавлен'
export const MSG_MEMBER_DELETED = 'Участник удален'
export const MSG_EVENT_DELETED = 'Событие удалено'
export const MSG_PRODUCT_ADDED = 'Продукт успешно добавлен'
export const MSG_LOGOUT_SUCCESS = 'Вы вышли из системы'
